#
# Module manifest for module 'SubscriptionExporter'
# Generated by: Laurie Rhodes
# Created: 2025-01-31
# Updated: 2025-09-27
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'SubscriptionExporter.psm1'

# Version number of this module.
ModuleVersion = '1.1.1'

# Supported PSEditions
CompatiblePSEditions = @('Desktop', 'Core')

# ID used to uniquely identify this module
GUID = '5b9c3d4e-2f5g-6789-abcd-ef0123456789'

# Author of this module
Author = 'Laurie Rhodes'

# Company or vendor of this module
CompanyName = 'Enterprise'

# Copyright statement for this module
Copyright = 'Laurie Rhodes under MIT License'

# Description of the functionality provided by this module
Description = 'Azure Subscription data export module for Azure Data Explorer integration via Event Hub. Features configuration-driven exports and YAML-based subscription management.'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.1'

# Minimum version of the common language runtime (CLR) required by this module
CLRVersion = '4.0'

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @(
    # Core orchestration
    'Invoke-SubscriptionDataExport',
    'Invoke-MultiSubscriptionDataExport',
    'Invoke-ConfigDrivenSubscriptionExport',
    
    # Configuration management
    'Get-SubscriptionExportConfig',
    
    # Data export modules
    'Export-AzureSubscriptionResources',
    'Export-AzureResourceGroups', 
    'Export-AzureChildResources',
    
    # Discovery and API utilities
    'Get-AzureAPIVersions',
    'Get-AzureResourceEndpoints',
    'Clean-AzureResourceObject',
    
    # Authentication (updated for ARM)
    'Get-AzureARMToken',
    
    # Event Hub integration (reused from AAD project)
    'Send-EventsToEventHub',
    
    # Error handling and resilience
    'Invoke-WithRetry',
    'Get-ErrorType',
    
    # Telemetry and monitoring
    'Write-CustomTelemetry',
    'Write-ExportProgress',
    'New-CorrelationContext',
    
    # Storage utilities (reused)
    'Get-AzTableStorageData',
    'Set-AzTableStorageData',
    'Get-Events',
    'Get-StorageTableValue',
    'Push-StorageTableValue'
)

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('Azure', 'Subscription', 'ARM', 'EventHub', 'DataExport', 'ADX', 'Resources', 'Telemetry', 'Enterprise', 'Configuration', 'YAML')

        # ReleaseNotes of this module
        ReleaseNotes = @'
Version 1.1.1 - Bug Fixes:
- FIXED: Missing utility functions (New-CorrelationContext, Write-CustomTelemetry, etc.)
- FIXED: Module export list updated to include all required functions
- FIXED: PowerShell syntax errors in configuration functions
- ENHANCED: Better error handling and logging during module load
- ENHANCED: Critical function availability checking

Version 1.1 - Configuration Management:
- NEW: YAML-based configuration file support for subscription management
- NEW: Invoke-ConfigDrivenSubscriptionExport for file-based configuration
- NEW: Get-SubscriptionExportConfig with built-in YAML parser
- NEW: Automatic fallback to environment variables when config files unavailable
- NEW: Support for subscription priorities, filters, and advanced settings
- ENHANCED: Timer and HTTP triggers automatically detect and use appropriate export mode
- IMPROVED: Configuration validation and error handling throughout
- EXAMPLE: Initial subscription 2be53ae5-6e46-47df-beb9-6f3a795387b8 configured

Version 1.0 - Initial Release:
- Azure Subscription resource export functionality
- Dynamic API version discovery from Azure ARM
- Intelligent child resource discovery and export
- Resource-specific object cleaning and optimization
- Modular architecture based on proven backup script
- Comprehensive telemetry and performance monitoring
- Event Hub streaming for Azure Data Explorer integration
- Support for configurable export scopes and filters
'@

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}